export const MAX_PREVIEW_ASSET_BYTES = 4 * 1024 * 1024
export const MAX_PREVIEW_ASSET_ATTEMPTS = 8
export const MAX_PREVIEW_ASSET_CONCURRENCY = 3
export const MAX_PREVIEW_ASSET_WINDOW_BYTES = 12 * 1024 * 1024
export const PREVIEW_ASSET_WINDOW_MS = 60_000
export const PREVIEW_ASSET_RESERVATION_TTL_MS = 45_000
