"use server"

import { compile } from "@mdx-js/mdx"
import { remarkTransformImports, ExtractedImport } from "./transformImports"

export interface CompileMdxResult {
  code?: string
  error?: string
  imports?: ExtractedImport[]
}

export async function compileMdx(source: string, allowedImports: Record<string, string[]>): Promise<CompileMdxResult> {
  try {
    const vfile = await compile(source, {
      outputFormat: "function-body",
      remarkPlugins: [[remarkTransformImports, { allowedImports }]],
      development: false,
    })

    const imports = vfile.data.extractedImports as ExtractedImport[] | undefined

    // MDX strictly throws when a component isn't provided.
    // We want our proxy to handle missing components gracefully (rendering placeholders).
    // So we strip out the hard throw statements generated by the MDX compiler.
    let code = String(vfile)
    code = code.replace(/if \(![a-zA-Z0-9_$]+\) _missingMdxReference\([^)]+\);/g, "")

    return {
      code,
      imports: imports || [],
    }
  } catch (error: any) {
    return {
      error: error.message || "Failed to compile MDX",
    }
  }
}
